# Generated by Django 2.1.2 on 2018-10-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Personal'), (2, 'Education'), (3, 'Community'), (4, 'Health & Medicine'), (5, 'Special Events')])),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_goal', models.DateField()),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Completed'), (3, 'Ended')])),
                ('amount_funded', models.FloatField(default=0)),
                ('amount_goal', models.FloatField()),
                ('creator_address', models.CharField(max_length=100)),
            ],
        ),
    ]
