# Generated by Django 2.1.2 on 2018-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Completed'), (3, 'Ended')], default=1),
        ),
    ]
