# Generated by Django 2.1.2 on 2018-10-23 05:26

from django.db import migrations, models
import fund.models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20181022_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_goal',
            field=models.FloatField(validators=[fund.models.validate_amount_goal]),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_goal',
            field=models.DateField(validators=[fund.models.validate_date_goal]),
        ),
    ]
