# Generated by Django 2.1.2 on 2018-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20181023_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Personal'), (2, 'Education'), (3, 'Community'), (4, 'Health & Medicine'), (5, 'Others')]),
        ),
    ]
