# Generated by Django 2.1.2 on 2018-10-24 14:31

from django.db import migrations, models
import fund.models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20181024_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator_address',
            field=models.CharField(max_length=100, validators=[fund.models.validate_creator_address]),
        ),
    ]
